// no controla errores de sintexis 
try {
        asdasdasd
} catch (error) {
        console.log("Lo siento paso un error de referencia")
}